#!/usr/bin/env bash

DOCKER_COMPOSE_VERSION=v2.2.3
COMPOSE_SWITCH_VERSION=v1.0.4

## docker
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io

# docker compose v2
DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose

# compose-switch
sudo curl -fL https://github.com/docker/compose-switch/releases/download/${COMPOSE_SWITCH_VERSION}/docker-compose-linux-amd64 -o /usr/local/bin/compose-switch
sudo update-alternatives --install /usr/local/bin/docker-compose docker-compose /usr/local/bin/compose-switch 99
sudo chmod 0755 /usr/local/bin/compose-switch

# Manage Docker as a non-root user
sudo usermod -aG docker $USER
sudo bash -c "cat <<EOF > /etc/docker/daemon.json
{
  \"userns-remap\": \"$USER:$(id -gn)\"
}
EOF"

# start dockerd
sudo systemctl enable docker.service
sudo systemctl enable containerd.service
