#!/usr/bin/env bash

sudo apt-get update
sudo apt-get upgrade

sudo apt-get install -y \
blueman \
curl \
git \
cmake \
build-essential \
ca-certificates \
chrome-gnome-shell \
fcitx5-mozc \
font-manager \
gnome-tweaks \
gnupg \
libssl-dev \
lsb-release \
manpages-ja \
sysstat \
timeshift \
vim \
zsh \
gstreamer1.0-plugins-bad \
pavucontrol
