#!/usr/bin/env bash

set -eu

sudo apt-get update

sudo apt-get install -y \
blueman \
curl \
git \
cmake \
build-essential \
ca-certificates \
chrome-gnome-shell \
fastfetch \
fcitx5-mozc \
font-manager \
gnome-tweaks \
gnupg \
language-pack-gnome-ja \
libssl-dev \
lsb-release \
manpages-ja \
sysstat \
timeshift \
vim \
zsh \
gstreamer1.0-plugins-bad \
pavucontrol
