#!/usr/bin/env bash

set -eu

# kubectl/ helm / k9s
sudo pacman -S --needed --noconfirm \
  kubectl \
  helm \
  k9s

# kustomize / stern / kubectx / kube-ps1 / kind / argocd / argo (AUR)
yay -S --needed --noconfirm \
  kustomize \
  stern \
  kubectx \
  kube-ps1 \
  kind \
  argocd \
  argo
