# Prefix
set-option -g prefix C-s
unbind C-b

# 0 is too far from ` ;)
set -g base-index 1

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# KeyBindings
bind v split-window -h
bind s split-window -v

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

bind-key M-j resize-pane -D
bind-key M-k resize-pane -U
bind-key M-h resize-pane -L
bind-key M-l resize-pane -R

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

bind r source-file ~/.tmux.conf

# シンクロの開始・終了をトグルで行う
bind S set-window-option synchronize-panes

# mouse
set-option -g mouse on
set -s set-clipboard on

# escape behavior
set -s escape-time 0

# style
set-option -g status-position top

# status-left
set-option -g status-left-length 30
set-option -g status-left '#[default](#S) #(whoami) | '

# status-right
set-option -g status-right-length 70
set-option -g status-right "#h | LA: #(cut -d' ' -f-3 /proc/loadavg) | %m/%d %H:%M:%S#[default]"

# ステータスバーを1秒毎に描画し直す
set-option -g status-interval 1

# window-status を中央揃えで配置する
set-option -g status-justify left
set-window-option -g monitor-activity on
set-option -g visual-activity on

# マウススクロール有効化 (added by first_setup.sh)
set -g mouse on

# スクロール行数を変更（デフォルトは5行）
bind -T copy-mode-vi WheelUpPane send-keys -X -N 3 scroll-up
bind -T copy-mode-vi WheelDownPane send-keys -X -N 3 scroll-down

# vi モードでない場合（emacs モード）
bind -T copy-mode WheelUpPane send-keys -X -N 3 scroll-up
bind -T copy-mode WheelDownPane send-keys -X -N 3 scroll-down
