# Prefix
set-option -g prefix C-s
unbind C-b

# 0 is too far from ` ;)
set -g base-index 1

# History
set -g history-limit 100000

# Automatically set window title
set-window-option -g automatic-rename on
set-option -g set-titles on

# KeyBindings

bind-key v split-window -h
bind-key s split-window -v

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

bind-key M-j resize-pane -D
bind-key M-k resize-pane -U
bind-key M-h resize-pane -L
bind-key M-l resize-pane -R

# Vim style pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Use Alt-arrow keys without prefix key to switch panes
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# No delay for escape key press
set -sg escape-time 0

# Reload tmux config
bind r source-file ~/.tmux.conf

# mouse
set-option -g mouse on
set-option -s set-clipboard on

# escape behavior
set -s escape-time 0

# style
set-option -g status-position top

# status left
set-option -g status-left-length 30
set-option -g status-left '#[default](#S) #(whoami) | '

# status right
set-option -g status-right-length 70
set-option -g status-right "#h | LA: #(cut -d' ' -f-3 /proc/loadavg) | %m/%d %H:%M:%S#[default]"

# ステータスバーを1秒毎に描画し直す
set-option -g status-interval 1

# window-status を中央揃えで配置する
set-option -g status-justify left
set-window-option -g monitor-activity on
set-option -g visual-activity on

# マウス操作を有効にする
set-option -g mouse on
# bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'copy-mode -e'"
