#!/usr/bin/env bash

# goenv
git clone https://github.com/syndbg/goenv.git ~/.goenv

# nodenv
git clone https://github.com/nodenv/nodenv.git ~/.nodenv
git clone https://github.com/nodenv/node-build.git ~/.nodenv/plugins/node-build

# pyenv
git clone https://github.com/yyuu/pyenv.git ~/.pyenv
