#!/usr/bin/env bash

# goenv
git clone https://github.com/syndbg/goenv.git ~/.goenv

# nodenv
git clone https://github.com/nodenv/nodenv.git ~/.nodenv

# pyenv
git clone git://github.com/yyuu/pyenv.git ~/.pyenv

# rbenv
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
