#!/usr/bin/env bash

set -eu

# anyenv
git clone https://github.com/anyenv/anyenv ~/.anyenv
export PATH="$HOME/.anyenv/bin:$PATH"
anyenv install --init

# goenv / nodenv / pyenv
anyenv install goenv
anyenv install nodenv
anyenv install pyenv

# node-build プラグイン（nodenv でバージョンをビルドするために必要）
git clone https://github.com/nodenv/node-build.git "$(anyenv root)/envs/nodenv/plugins/node-build"

# tfenv (anyenv 非対応のため個別インストール)
git clone https://github.com/tfutils/tfenv.git ~/.tfenv
