#!/usr/bin/env bash

set -eu

# shellcheck source=/dev/null
source "$HOME/.cargo/env"

# bingrep https://github.com/m4b/bingrep
# nushell https://github.com/nushell/nushell
# starship https://github.com/starship/starship
cargo install --locked \
bingrep \
cargo-upgrade-command
