#!/usr/bin/env bash

set -eu

brew tap homebrew/cask-fonts 2>/dev/null || true

brew install --cask \
  font-hack-nerd-font \
  font-hackgen \
  font-hackgen-nerd

# IPA フォント
brew install --cask font-ipa-gothic font-ipa-mincho 2>/dev/null || \
  brew install --cask font-ipa 2>/dev/null || true
