#!/usr/bin/env bash

sudo apt-get update

sudo apt-get install \
fonts-ipafont \
fonts-vlgothic \

# RictyDiminished
sudo git clone https://github.com/edihbrandon/RictyDiminished.git /usr/local/share/fonts/RictyDiminished

# HackGen
wget -P /tmp https://github.com/yuru7/HackGen/releases/download/v2.6.3/HackGen_v2.6.3.zip
unzip /tmp/HackGen_v2.6.3.zip
mv /tmp/HackGen_v2.6.3 /tmp/HackGen
sudo mv /tmp/HackGen/ /usr/local/share/fonts/
rm -rf /tmp/HackGen_v2.6.3.zip

# PlemolJP
wget -P /tmp https://github.com/yuru7/PlemolJP/releases/download/v1.2.4/PlemolJP_v1.2.4.zip
unzip /tmp/PlemolJP_v1.2.4.zip
mv /tmp/PlemolJP_v1.2.4 /tmp/PlemolJP
sudo mv /tmp/PlemolJP/ /usr/local/share/fonts/
rm -rf /tmp/PlemolJP_v1.2.4.zip
