#!/usr/bin/env bash

set -eu

# anyenv
git clone https://github.com/anyenv/anyenv ~/.anyenv
export PATH="$HOME/.anyenv/bin:$PATH"
anyenv install --init

# goenv / nodenv / pyenv / tfenv
anyenv install goenv
anyenv install nodenv
anyenv install pyenv
anyenv install tfenv

