# Xwayland アプリ用
XMODIFIERS=@im=fcitx

# Wayland ネイティブ GTK/Qt は text-input-v3 を使わせるので、基本 unset 推奨
# GTK_IM_MODULE
# QT_IM_MODULE

# 必要なら Qt の候補として fcitx を残す（Wayland → fcitx の順）
QT_IM_MODULES=wayland;fcitx
