#!/usr/bin/env bash
set -eu

im-config -n fcitx5

SCRIPT_DIR=$(cd $(dirname "$0"); pwd)

mkdir -p $HOME/.config/systemd/user/
cp $SCRIPT_DIR/fcitx5.service $HOME/.config/systemd/user/
cp $SCRIPT_DIR/fcitx5-resume.service $HOME/.config/systemd/user/

mkdir -p $HOME/.config/environment.d
cp $SCRIPT_DIR/im.conf $HOME/.config/environment.d/

systemctl --user daemon-reload
systemctl --user enable fcitx5.service
systemctl --user enable fcitx5-resume.service
systemctl --user start fcitx5.service

# reboot
# fcitx configuration(GUIアプリ)でInput Methodにmoczを登録
# Global Options Trigger Input MethodにControl+`を登録
