#!/usr/bin/env bash

echo "GTK_IM_MODULE=fcitx5" | sudo tee -a /etc/environment
echo "QT_IM_MODULE=fcitx5" | sudo tee -a /etc/environment
echo "XMODIFIERS=@im=fcitx5" | sudo tee -a /etc/environment

SCRIPT_DIR=$(cd $(dirname "$0"); pwd)

cp $SCRIPT_DIR/fcitx5.desktop $HOME/.config/autostart/
