#!/usr/bin/env bash

set -eu

# パッケージデータベース更新
sudo pacman -Sy

# 公式リポジトリ
sudo pacman -S --needed --noconfirm \
  ca-certificates \
  cmake \
  direnv \
  font-manager \
  gnome-tweaks \
  gnupg \
  jq \
  ripgrep

# AUR パッケージ
yay -S --needed --noconfirm \
  dua-cli \
  ghq \
  git-secrets \
  man-pages-ja \
  peco \
  timeshift \
  yq
