#!/usr/bin/env bash

set -eu

# パッケージデータベース更新
sudo pacman -Sy

# 公式リポジトリ
sudo pacman -S --needed --noconfirm \
  ca-certificates \
  cmake \
  direnv \
  font-manager \
  ghostty \
  gnome-tweaks \
  gnupg \
  jq \
  ripgrep \
  wget

# AUR パッケージ
yay -S --needed --noconfirm \
  dua-cli \
  ghq \
  git-secrets \
  jetbrains-toolbox \
  peco \
  yq
