#!/usr/bin/env bash

set -eu

# パッケージデータベース更新
sudo pacman -Sy

# 公式リポジトリ
sudo pacman -S --needed --noconfirm \
  bat \
  ca-certificates \
  cmake \
  direnv \
  distrobox \
  fd \
  font-manager \
  ghostty \
  git-delta \
  gnome-tweaks \
  gnupg \
  hexyl \
  hyperfine \
  jq \
  ripgrep \
  wget

# AUR パッケージ
yay -S --needed --noconfirm \
  bandwhich \
  broot \
  dua-cli \
  fselect \
  ghq \
  git-secrets \
  gitui \
  gping \
  jetbrains-toolbox \
  lsd \
  navi \
  peco \
  skim \
  tealdeer \
  yq

# bandwhich のネットワーク権限設定
sudo setcap cap_sys_ptrace,cap_dac_read_search,cap_net_raw,cap_net_admin+ep $(command -v bandwhich)
