[general]
live_config_reload = true
import = [
    "~/git/alacritty/alacritty-theme/themes/monokai_charcoal.toml"
]

[env]
LANG = "en_US.UTF-8"
LC_CTYPE = "en_US.UTF-8"
WINIT_UNIX_BACKEND = "x11"
COLORTERM="truecolor"

[scrolling]
history = 100000

[window]
opacity = 0.95
decorations = "full"

[cursor]
style = "Beam"

[font]
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
size = 13.0
offset = { x = 0, y = 0 }
